config/routes.rb
Mauli::Application.routes.draw do

  get "transactions/add_total_amount"
  post "transactions/add_amount"
  resources :transactions 

  get "transactions/new" 
  get "add_user/do_transaction"
  get "add_user/delete_transaction"
  get "add_user/add_buyer"
  post "add_user/add_user_db"
  get "add_user/main_amount"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post "images/add_image"
  post "images/add_image_project"

  get "images/add_image_project_view"

  get "images/add"
  get "flats/all_flats"

  get "flats/all_images"
  get "flats/all_images_project"
    

  resources :hks

  resources :floors

  resources :bbhks

  resources :flats

  resources :bhks

  resources :projects

end

app/models/flat.rb
class Flat < ActiveRecord::Base
	belongs_to :project
	has_many :images
	belongs_to :buyer
	has_many :transactions
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  def all_flats
  @id = params[:id]
  @flats = Flat.where(:project_id => @id)
  #@flats2 = Hk.where(:project_id => @id)
  #@flats = @flats1+@flats2
  respond_to do |format|
    format.json {render json: @flats.to_json }
    format.html {render action: 'all_flats' }
    #format.html {render json: @flats.to_json }
  end
end

  #   def all_images
  #      @urls = Array.new
   #     @flat_id = params[:flat_id];
  #      @images = Images.where(:flat_id => @flat_id)
  #      @images.each do |image|
  #      @urls << {:url => image.photo.url,:details => image.details} 
  #   end
  #     respond_to do |format|
  #     format.json { render text: @urls.to_json }    
  #   end
  # end

    def all_images_project
      @urls = Array.new
      @project = params[:project_id]
      @images = PImage.where(:project_id => @project)
      @images.each do |image|
      @urls << {:url => image.photo.url,:details => image.details}
  end
      respond_to do |format|
      format.json { render text: @urls.to_json }    
    end
end


  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'flat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flat }
      else
        format.html { render action: 'new' }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'flat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:hall_size, :bed_size, :kitchen_size, :floor, :sold_out, :status,:info,:name,:project_id,:salable_area,:details)
    end

#------------------------------------------------------

end    

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :hall_size %>
  <%= f.input :bed1_size %>
  <%= f.input :bed2_size %>
  <%= f.input :salable_area %>
  <%= f.input :details %>
  <%= f.input :info ,:collection => ["HK","BHK","2BHK","3BHK" ]%>
  <%= f.input :kitchen_size %>
  <%= f.input :floor, :collection => ["Ground","First","Second","Third","Fourth"] %>
  <%= f.input :sold_out %>
  <%= f.association :project, :include_blank => false %>
  <%= f.input :status %>
  <%= f.button :submit, :class => 'btn-primary' %>
    
<% end %>

app/views/flats/all_flats.html.erb
<h1>Listing bhks</h1>
<table>
  <thead>
    <tr>
      <th>Hall size</th>
      <th>Bed size</th>
      <th>Kitchen size</th>
      <th>Size</th>
      <th>Floor</th>
      <th>Sold out</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
      <th>Transaction</th>
    </tr>
  </thead>
  <tbody>
  <% unless @flats.nil? %>
    <% @flats.each do |bhk| %>
      <tr>
        <td><%= bhk.hall_size %></td>
        <td><%= bhk.kitchen_size %></td>
        <td><%= bhk.floor %></td>
        <td><%= bhk.sold_out %></td>
        <td><%= bhk.status %></td>
        <td><%= link_to 'Show', bhk %></td>
        <td><%= link_to 'Edit', edit_flat_path(bhk) %></td>
        <td><%= link_to 'Destroy', bhk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td></td>
        <td></td>
        <% if bhk.sold_out %>
        <td><%= link_to 'Make Transaction', new_transaction_path(:id=> bhk.id,:balance_amount => bhk.balance_amount) %></td>
        <% else %>
        <td><%= link_to 'Sell', new_transaction_path(:id=> bhk.id,:balance_amount=> bhk.balance_amount) %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
   <% end -%>
</table>

<br>

<%= link_to 'New Flat', new_flat_path %>

app/views/flats/edit.html.erb
<h1>Editing bhk</h1>

<%= render 'form' %>

<%= link_to 'Show', @bhk %> |
<%= link_to 'Back', bhks_path %>

app/views/flats/index.html.erb
<h1>Listing flats</h1>

<table>
  <thead>
    <tr>
      <th>Hall size</th>
      <th>Bed size</th>
      <th>Kitchen size</th>
      <th>Size</th>
      <th>Floor</th>
      <th>Sold out</th>

      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.hall_size %></td>
        <td><%= flat.bed1_size %></td>
        <td><%= flat.kitchen_size %></td>
        <td><%= flat.info %></td>
        <td><%= flat.floor %></td>
        <td><%= flat.sold_out %></td>
        <td><%= flat.status %></td>
        <td><%= link_to 'Show', flat %></td>
        <td><%= link_to 'Edit', edit_flat_path(flat) %></td>
        <td><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New flat', new_flat_path %>

app/views/flats/new.html.erb
<h1>New bhk</h1>

<%= render 'form' %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hall size:</strong>
  <%= @flat.hall_size %>
</p>

<p>
  <strong>Bed size:</strong>
  <%= @flat.bed1_size %>
</p>

<p>
  <strong>Kitchen size:</strong>
  <%= @flat.kitchen_size %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @flat.floor %>
</p>

<p>
  <strong>Sold out:</strong>
  <%= @flat.sold_out %>
</p>

<p>
  <strong>Status:</strong>
  <%= @flat.status %>
</p>

<%= link_to 'Edit', edit_flat_path(@flat) %> |
<%= link_to 'Back', flats_path %>