config/routes.rb
Mauli::Application.routes.draw do

  get "transactions/add_total_amount"
  post "transactions/add_amount"
  resources :transactions 

  get "transactions/new" 
  get "add_user/do_transaction"
  get "add_user/delete_transaction"
  get "add_user/add_buyer"
  post "add_user/add_user_db"
  get "add_user/main_amount"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post "images/add_image"
  post "images/add_image_project"

  get "images/add_image_project_view"

  get "images/add"
  get "flats/all_flats"

  get "flats/all_images"
  get "flats/all_images_project"
    

  resources :hks

  resources :floors

  resources :bbhks

  resources :flats

  resources :bhks

  resources :projects

end

app/models/bbhk.rb
class Bbhk < ActiveRecord::Base
	belongs_to :project
	belongs_to :buyer
end

app/models/bhk.rb
class Bhk < ActiveRecord::Base
	belongs_to :project
	has_many :images
	belongs_to :buyer
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
	has_many :bhks
	has_many :hks
	has_many :bbhks
end

app/models/flat.rb
class Flat < ActiveRecord::Base
	belongs_to :project
	has_many :images
	belongs_to :buyer
	has_many :transactions
end

app/models/floor.rb
class Floor < ActiveRecord::Base
	belongs_to :project
end

app/models/hk.rb
class Hk < ActiveRecord::Base
	belongs_to :project
	belongs_to :buyer
end

app/models/images.rb
class Images < ActiveRecord::Base

	has_attached_file :photo ,:style => {:medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	belongs_to :bhk
end

app/models/p_image.rb
class PImage < ActiveRecord::Base
has_attached_file :photo ,:style => {:medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	belongs_to :project

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :bbhks
	has_many :hks
	has_many :bhks
	has_one :floor
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :flat
end

app/controllers/bbhks_controller.rb
class BbhksController < ApplicationController
  before_action :set_bbhk, only: [:show, :edit, :update, :destroy]

  # GET /bbhks
  # GET /bbhks.json
  def index
    @bbhks = Bbhk.all
  end

  # GET /bbhks/1
  # GET /bbhks/1.json
  def show
  end

  # GET /bbhks/new
  def new
    @bbhk = Bbhk.new
  end

  # GET /bbhks/1/edit
  def edit
  end

  # POST /bbhks
  # POST /bbhks.json
  def create
    @bbhk = Bbhk.new(bbhk_params)

    respond_to do |format|
      if @bbhk.save
        format.html { redirect_to @bbhk, notice: 'Bbhk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bbhk }
      else
        format.html { render action: 'new' }
        format.json { render json: @bbhk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bbhks/1
  # PATCH/PUT /bbhks/1.json
  def update
    respond_to do |format|
      if @bbhk.update(bbhk_params)
        format.html { redirect_to @bbhk, notice: 'Bbhk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bbhk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bbhks/1
  # DELETE /bbhks/1.json
  def destroy
    @bbhk.destroy
    respond_to do |format|
      format.html { redirect_to bbhks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bbhk
      @bbhk = Bbhk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bbhk_params
      params.require(:bbhk).permit(:hall_size, :bed1_size, :bed2_size, :kitchen_size, :floor, :sold_out, :status)
    end
end

app/controllers/bhks_controller.rb
class BhksController < ApplicationController
  before_action :set_bhk, only: [:show, :edit, :update, :destroy]

  # GET /bhks
  # GET /bhks.json
  def index
    @bhks = Bhk.all
  end

  # GET /bhks/1
  # GET /bhks/1.json
  def show
  end

  # GET /bhks/new
  def new
    @bhk = Bhk.new
  end

  # GET /bhks/1/edit
  def edit
  end

  # POST /bhks
  # POST /bhks.json
  def create
    @bhk = Bhk.new(bhk_params)

    respond_to do |format|
      if @bhk.save
        format.html { redirect_to @bhk, notice: 'Bhk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bhk }
      else
        format.html { render action: 'new' }
        format.json { render json: @bhk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bhks/1
  # PATCH/PUT /bhks/1.json
  def update
    respond_to do |format|
      if @bhk.update(bhk_params)
        format.html { redirect_to @bhk, notice: 'Bhk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bhk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bhks/1
  # DELETE /bhks/1.json
  def destroy
    @bhk.destroy
    respond_to do |format|
      format.html { redirect_to bhks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bhk
      @bhk = Bhk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bhk_params
      params.require(:bhk).permit(:hall_size, :bed_size, :kitchen_size, :floor, :sold_out, :status,:info,:name,:project_id,:salable_area,:details)
    end
end

app/controllers/hks_controller.rb
class HksController < ApplicationController
  before_action :set_hk, only: [:show, :edit, :update, :destroy]

  # GET /hks
  # GET /hks.json
  def index
    @hks = Hk.all
  end

  # GET /hks/1
  # GET /hks/1.json
  def show
  end

  # GET /hks/new
  def new
    @hk = Hk.new
  end

  # GET /hks/1/edit
  def edit
  end

  # POST /hks
  # POST /hks.json
  def create
    @hk = Hk.new(hk_params)

    respond_to do |format|
      if @hk.save
        format.html { redirect_to @hk, notice: 'Hk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hk }
      else
        format.html { render action: 'new' }
        format.json { render json: @hk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hks/1
  # PATCH/PUT /hks/1.json
  def update
    respond_to do |format|
      if @hk.update(hk_params)
        format.html { redirect_to @hk, notice: 'Hk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hks/1
  # DELETE /hks/1.json
  def destroy
    @hk.destroy
    respond_to do |format|
      format.html { redirect_to hks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hk
      @hk = Hk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hk_params
      params.require(:hk).permit(:hall_size, :kitchen_size, :floor, :sold_out, :status,:project_id)
    end
end

app/helpers/add_user_helper.rb
module AddUserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbh_ks_helper.rb
module BbhKsHelper
end

app/helpers/bh_ks_helper.rb
module BhKsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/helpers/h_ks_helper.rb
module HKsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/bbhks/_form.html.erb
<%= form_for(@bbhk) do |f| %>
  <% if @bbhk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bbhk.errors.count, "error") %> prohibited this bbhk from being saved:</h2>

      <ul>
      <% @bbhk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hall_size %><br>
    <%= f.text_field :hall_size %>
  </div>
  <div class="field">
    <%= f.label :bed1_size %><br>
    <%= f.text_field :bed1_size %>
  </div>
  <div class="field">
    <%= f.label :bed2_size %><br>
    <%= f.text_field :bed2_size %>
  </div>
  <div class="field">
    <%= f.label :kitchen_size %><br>
    <%= f.text_field :kitchen_size %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.text_field :floor %>
  </div>
  <div class="field">
    <%= f.label :sold_out %><br>
    <%= f.check_box :sold_out %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bbhks/edit.html.erb
<h1>Editing bbhk</h1>

<%= render 'form' %>

<%= link_to 'Show', @bbhk %> |
<%= link_to 'Back', bbhks_path %>

app/views/bbhks/index.html.erb
<h1>Listing bbhks</h1>

<table>
  <thead>
    <tr>
      <th>Hall size</th>
      <th>Bed1 size</th>
      <th>Bed2 size</th>
      <th>Kitchen size</th>
      <th>Floor</th>
      <th>Sold out</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bbhks.each do |bbhk| %>
      <tr>
        <td><%= bbhk.hall_size %></td>
        <td><%= bbhk.bed1_size %></td>
        <td><%= bbhk.bed2_size %></td>
        <td><%= bbhk.kitchen_size %></td>
        <td><%= bbhk.floor %></td>
        <td><%= bbhk.sold_out %></td>
        <td><%= bbhk.status %></td>
        <td><%= link_to 'Show', bbhk %></td>
        <td><%= link_to 'Edit', edit_bbhk_path(bbhk) %></td>
        <td><%= link_to 'Destroy', bbhk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bbhk', new_bbhk_path %>

app/views/bbhks/new.html.erb
<h1>New bbhk</h1>

<%= render 'form' %>

<%= link_to 'Back', bbhks_path %>

app/views/bbhks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hall size:</strong>
  <%= @bbhk.hall_size %>
</p>

<p>
  <strong>Bed1 size:</strong>
  <%= @bbhk.bed1_size %>
</p>

<p>
  <strong>Bed2 size:</strong>
  <%= @bbhk.bed2_size %>
</p>

<p>
  <strong>Kitchen size:</strong>
  <%= @bbhk.kitchen_size %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @bbhk.floor %>
</p>

<p>
  <strong>Sold out:</strong>
  <%= @bbhk.sold_out %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bbhk.status %>
</p>

<%= link_to 'Edit', edit_bbhk_path(@bbhk) %> |
<%= link_to 'Back', bbhks_path %>

app/views/bhks/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :hall_size %>
  <%= f.input :bed_size %>
  <%= f.input :salable_area %>
  <%= f.input :details %>
  <%= f.input :info ,:collection => ["HK","BHK","2BHK","3BHK" ]%>
  <%= f.input :kitchen_size %>
  <%= f.input :floor, :collection => ["Ground","First","Second","Third","Fourth"] %>
  <%= f.input :sold_out %>
  <%= f.association :project, :include_blank => false %>
  <%= f.input :status %>
  <%= f.button :submit, :class => 'btn-primary' %>
    
<% end %>

app/views/bhks/edit.html.erb
<h1>Editing bhk</h1>

<%= render 'form' %>

<%= link_to 'Show', @bhk %> |
<%= link_to 'Back', bhks_path %>

app/views/bhks/index.html.erb
<h1>Listing bhks</h1>

<table>
  <thead>
    <tr>
      <th>Hall size</th>
      <th>Bed size</th>
      <th>Kitchen size</th>
      <th>Size</th>
      <th>Floor</th>
      <th>Sold out</th>

      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bhks.each do |bhk| %>
      <tr>
        <td><%= bhk.hall_size %></td>
        <td><%= bhk.bed_size %></td>
        <td><%= bhk.kitchen_size %></td>
        <td><%= bhk.info %></td>
        <td><%= bhk.floor %></td>
        <td><%= bhk.sold_out %></td>
        <td><%= bhk.status %></td>
        <td><%= link_to 'Show', bhk %></td>
        <td><%= link_to 'Edit', edit_bhk_path(bhk) %></td>
        <td><%= link_to 'Destroy', bhk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bhk', new_bhk_path %>

app/views/bhks/new.html.erb
<h1>New bhk</h1>

<%= render 'form' %>

<%= link_to 'Back', bhks_path %>

app/views/bhks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hall size:</strong>
  <%= @bhk.hall_size %>
</p>

<p>
  <strong>Bed size:</strong>
  <%= @bhk.bed_size %>
</p>

<p>
  <strong>Kitchen size:</strong>
  <%= @bhk.kitchen_size %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @bhk.floor %>
</p>

<p>
  <strong>Sold out:</strong>
  <%= @bhk.sold_out %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bhk.status %>
</p>

<%= link_to 'Edit', edit_bhk_path(@bhk) %> |
<%= link_to 'Back', bhks_path %>

app/views/hks/_form.html.erb
<%= simple_form_for @hk do |f| %>
  <%= f.input :name %>
  <%= f.input :hall_size %>
  <%= f.input :kitchen_size %>
  <%= f.input :floor, :collection => ["Ground","First","Second","Third","Fourth"] %>
  <%= f.input :sold_out %>
  <%= f.association :project, :include_blank => false %>
  <%= f.input :status %>
  <%= f.button :submit, :class => 'btn-primary' %>
    
<% end %>

app/views/hks/edit.html.erb
<h1>Editing hk</h1>

<%= render 'form' %>

<%= link_to 'Show', @hk %> |
<%= link_to 'Back', hks_path %>

app/views/hks/index.html.erb
<h1>Listing hks</h1>

<table>
  <thead>
    <tr>
      <th>Hall size</th>
      <th>Kitchen size</th>
      <th>Floor</th>
      <th>Sold out</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hks.each do |hk| %>
      <tr>
        <td><%= hk.hall_size %></td>
        <td><%= hk.kitchen_size %></td>
        <td><%= hk.floor %></td>
        <td><%= hk.sold_out %></td>
        <td><%= hk.status %></td>
        <td><%= link_to 'Show', hk %></td>
        <td><%= link_to 'Edit', edit_hk_path(hk) %></td>
        <td><%= link_to 'Destroy', hk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hk', new_hk_path %>

app/views/hks/new.html.erb
<h1>New hk</h1>

<%= render 'form' %>

<%= link_to 'Back', hks_path %>

app/views/hks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hall size:</strong>
  <%= @hk.hall_size %>
</p>

<p>
  <strong>Kitchen size:</strong>
  <%= @hk.kitchen_size %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @hk.floor %>
</p>

<p>
  <strong>Sold out:</strong>
  <%= @hk.sold_out %>
</p>

<p>
  <strong>Status:</strong>
  <%= @hk.status %>
</p>

<%= link_to 'Edit', edit_hk_path(@hk) %> |
<%= link_to 'Back', hks_path %>