config/routes.rb
Mauli::Application.routes.draw do

  get "transactions/add_total_amount"
  post "transactions/add_amount"
  resources :transactions 

  get "transactions/new" 
  get "add_user/do_transaction"
  get "add_user/delete_transaction"
  get "add_user/add_buyer"
  post "add_user/add_user_db"
  get "add_user/main_amount"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post "images/add_image"
  post "images/add_image_project"

  get "images/add_image_project_view"

  get "images/add"
  get "flats/all_flats"

  get "flats/all_images"
  get "flats/all_images_project"
    

  resources :hks

  resources :floors

  resources :bbhks

  resources :flats

  resources :bhks

  resources :projects

end

app/models/bbhk.rb
class Bbhk < ActiveRecord::Base
	belongs_to :project
	belongs_to :buyer
end

app/models/bhk.rb
class Bhk < ActiveRecord::Base
	belongs_to :project
	has_many :images
	belongs_to :buyer
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
	has_many :bhks
	has_many :hks
	has_many :bbhks
end

app/models/flat.rb
class Flat < ActiveRecord::Base
	belongs_to :project
	has_many :images
	belongs_to :buyer
	has_many :transactions
end

app/models/floor.rb
class Floor < ActiveRecord::Base
	belongs_to :project
end

app/models/hk.rb
class Hk < ActiveRecord::Base
	belongs_to :project
	belongs_to :buyer
end

app/models/images.rb
class Images < ActiveRecord::Base

	has_attached_file :photo ,:style => {:medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	belongs_to :bhk
end

app/models/p_image.rb
class PImage < ActiveRecord::Base
has_attached_file :photo ,:style => {:medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	belongs_to :project

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :bbhks
	has_many :hks
	has_many :bhks
	has_one :floor
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :flat
end

app/controllers/bhks_controller.rb
class BhksController < ApplicationController
  before_action :set_bhk, only: [:show, :edit, :update, :destroy]

  # GET /bhks
  # GET /bhks.json
  def index
    @bhks = Bhk.all
  end

  # GET /bhks/1
  # GET /bhks/1.json
  def show
  end

  # GET /bhks/new
  def new
    @bhk = Bhk.new
  end

  # GET /bhks/1/edit
  def edit
  end

  # POST /bhks
  # POST /bhks.json
  def create
    @bhk = Bhk.new(bhk_params)

    respond_to do |format|
      if @bhk.save
        format.html { redirect_to @bhk, notice: 'Bhk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bhk }
      else
        format.html { render action: 'new' }
        format.json { render json: @bhk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bhks/1
  # PATCH/PUT /bhks/1.json
  def update
    respond_to do |format|
      if @bhk.update(bhk_params)
        format.html { redirect_to @bhk, notice: 'Bhk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bhk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bhks/1
  # DELETE /bhks/1.json
  def destroy
    @bhk.destroy
    respond_to do |format|
      format.html { redirect_to bhks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bhk
      @bhk = Bhk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bhk_params
      params.require(:bhk).permit(:hall_size, :bed_size, :kitchen_size, :floor, :sold_out, :status,:info,:name,:project_id,:salable_area,:details)
    end
end

app/controllers/hks_controller.rb
class HksController < ApplicationController
  before_action :set_hk, only: [:show, :edit, :update, :destroy]

  # GET /hks
  # GET /hks.json
  def index
    @hks = Hk.all
  end

  # GET /hks/1
  # GET /hks/1.json
  def show
  end

  # GET /hks/new
  def new
    @hk = Hk.new
  end

  # GET /hks/1/edit
  def edit
  end

  # POST /hks
  # POST /hks.json
  def create
    @hk = Hk.new(hk_params)

    respond_to do |format|
      if @hk.save
        format.html { redirect_to @hk, notice: 'Hk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hk }
      else
        format.html { render action: 'new' }
        format.json { render json: @hk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hks/1
  # PATCH/PUT /hks/1.json
  def update
    respond_to do |format|
      if @hk.update(hk_params)
        format.html { redirect_to @hk, notice: 'Hk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hks/1
  # DELETE /hks/1.json
  def destroy
    @hk.destroy
    respond_to do |format|
      format.html { redirect_to hks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hk
      @hk = Hk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hk_params
      params.require(:hk).permit(:hall_size, :kitchen_size, :floor, :sold_out, :status,:project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #before_action  only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
      end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @id = params[:id]

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save

        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :address, :no_of_flats,:details,:id)
    end
end

app/helpers/add_user_helper.rb
module AddUserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbh_ks_helper.rb
module BbhKsHelper
end

app/helpers/bh_ks_helper.rb
module BhKsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/helpers/h_ks_helper.rb
module HKsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
 
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :no_of_flats %><br>
    <%= f.number_field :no_of_flats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>No of flats</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name ,flats_all_flats_path(:id=>project.id)%></td>
        <td><%= project.address %></td>
        <td><%= project.no_of_flats %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

  <% @project = Project.find_by_id(@id) %>
<p>
  <strong>Name:</strong>
  <%=  @project.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @project.address %>
</p>

<p>
  <strong>No of flats:</strong>
  <%= @project.no_of_flats %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>