config/routes.rb
Mauli::Application.routes.draw do

  get "transactions/add_total_amount"
  post "transactions/add_amount"
  resources :transactions 

  get "transactions/new" 
  get "add_user/do_transaction"
  get "add_user/delete_transaction"
  get "add_user/add_buyer"
  post "add_user/add_user_db"
  get "add_user/main_amount"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post "images/add_image"
  post "images/add_image_project"

  get "images/add_image_project_view"

  get "images/add"
  get "flats/all_flats"

  get "flats/all_images"
  get "flats/all_images_project"
    

  resources :hks

  resources :floors

  resources :bbhks

  resources :flats

  resources :bhks

  resources :projects

end

app/models/bbhk.rb
class Bbhk < ActiveRecord::Base
	belongs_to :project
	belongs_to :buyer
end

app/models/bhk.rb
class Bhk < ActiveRecord::Base
	belongs_to :project
	has_many :images
	belongs_to :buyer
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
	has_many :bhks
	has_many :hks
	has_many :bbhks
end

app/models/flat.rb
class Flat < ActiveRecord::Base
	belongs_to :project
	has_many :images
	belongs_to :buyer
	has_many :transactions
end

app/models/floor.rb
class Floor < ActiveRecord::Base
	belongs_to :project
end

app/models/hk.rb
class Hk < ActiveRecord::Base
	belongs_to :project
	belongs_to :buyer
end

app/models/images.rb
class Images < ActiveRecord::Base

	has_attached_file :photo ,:style => {:medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	belongs_to :bhk
end

app/models/p_image.rb
class PImage < ActiveRecord::Base
has_attached_file :photo ,:style => {:medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	belongs_to :project

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :bbhks
	has_many :hks
	has_many :bhks
	has_one :floor
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :flat
end

app/controllers/hks_controller.rb
class HksController < ApplicationController
  before_action :set_hk, only: [:show, :edit, :update, :destroy]

  # GET /hks
  # GET /hks.json
  def index
    @hks = Hk.all
  end

  # GET /hks/1
  # GET /hks/1.json
  def show
  end

  # GET /hks/new
  def new
    @hk = Hk.new
  end

  # GET /hks/1/edit
  def edit
  end

  # POST /hks
  # POST /hks.json
  def create
    @hk = Hk.new(hk_params)

    respond_to do |format|
      if @hk.save
        format.html { redirect_to @hk, notice: 'Hk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hk }
      else
        format.html { render action: 'new' }
        format.json { render json: @hk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hks/1
  # PATCH/PUT /hks/1.json
  def update
    respond_to do |format|
      if @hk.update(hk_params)
        format.html { redirect_to @hk, notice: 'Hk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hks/1
  # DELETE /hks/1.json
  def destroy
    @hk.destroy
    respond_to do |format|
      format.html { redirect_to hks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hk
      @hk = Hk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hk_params
      params.require(:hk).permit(:hall_size, :kitchen_size, :floor, :sold_out, :status,:project_id)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find_by_id(params[:id])
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @transaction.flat = Flat.find_by_id(params[:id])
    
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @flat_details = Flat.find_by_id(transaction_params[:flat_id])
    @flat_details.balance_amount = @flat_details.balance_amount.to_i - transaction_params[:debit].to_i
    @transaction.balance = @flat_details.balance_amount
    @flat_details.save
    respond_to do |format|
      if @transaction.save

        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transaction }
      else
        format.html { render action: 'new' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end


def add_total_amount
  @flat_details = Flat.new
end

def add_amount 
  @flat = params[:flat][:flat_id]
  @flat_details = Flat.find_by_id(@flat)
  @flat_details.total_amount = params[:flat][:total_amount]
  @flat_details.balance_amount = params[:flat][:total_amount]
  
  if @flat_details.save
    redirect_to projects_path
  end
  end


  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      if params[:id].nil?
      @transaction = Transaction.find(params[:id])
    end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:balance, :credit, :debit,:flat_id,:balance_amount,:receipt_no,:check_no,:method)
    end
end

app/helpers/add_user_helper.rb
module AddUserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbh_ks_helper.rb
module BbhKsHelper
end

app/helpers/bh_ks_helper.rb
module BhKsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/helpers/h_ks_helper.rb
module HKsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= simple_form_for @transaction do |f| %>
  <%= f.input :debit,:placeholder=>"Enter paid amount" %>
  <%= f.input :method,:collection =>["Check","Cash"],:default=>"Cash" %>
  <%= f.input :receipt_no,:placeholder=>"Please enter manual receipt no" %>
  <%= f.input :check_no,:placeholder=>"If payment method is by Check" %>
  <%= f.input :flat ,:as=> :hidden , :input_html=>{:value => params[:id]} %>
  <%= f.input :flat_id ,:as=> :hidden , :input_html=>{:value => params[:id]} %>
  <%= f.button :submit, :class => 'btn-primary' %>
<% end %>

app/views/transactions/add_total_amount.html.erb
<%= simple_form_for(@flat_details,:url=>transactions_add_amount_path) do |f| %>
  <%= f.input :total_amount%>
  <%= f.input :flat_id, :as=> :hidden , :input_html=>{:value=>params[:flat_id]} %>
  <%= f.button :submit, :class => 'btn-primary' %>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <thead>
    <tr>
      <th>Balance</th>
      <th>Credit</th>
      <th>Debit</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.balance %></td>
        <td><%= transaction.credit %></td>
        <td><%= transaction.debit %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Balance:</strong>
  <%= @transaction.balance %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @transaction.credit %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @transaction.debit %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>